### ISSUE TITLE
Slow, collision-prone hash algorithm

### ISSUE THREAD

**Issue by aegamesi** [jweinst1/Rooster#1]
The hash function appears to be very slow-- it took 42 seconds on my computer to hash the OSX built in wordlist ('/usr/share/dict/words').
Additionally, it produced a massive number of collisions: out of 235886 hashes produced, only 1544 were unique.

Compare this to the built in MD5 hasher, which took a third of a second and produced 235886 unique hashes.

**Comment by jweinst1** [comment]
Hey Eli, where do you find this list of built in words? I can't find it and I am on OS X El Captain.

The speed is an issue, right now it runs in exponential time or slower because I am converting every string into an integer then converting back into an alphanumeric string.

The collisions your finding are strange though, I tested the hashing function on `[str(elem) for elem in range(2000)]` and found no collisions, completed in just over a second. I also did the same for N-permutations of the alphabet of length 3, such as 'aaa' then 'aab', etc and found no collisions.

**Comment by aegamesi** [comment]
Not sure why you can't find it-- it should be located at /usr/share/dict/words.

I really think you'd be better off using a previously developed hash function, like MD5 or SHA-1.

**Comment by jweinst1** [comment]
Found it, I guess you have to go to the doc through terminal, its invisible in finder.

I would, but I find it more fun to try and make my own hash function.
